config/routes.rb
HuddleUp::Application.routes.draw do

  get 'home/index'
  get '/errors/error_404'
  get '/errors/error_500'
  get '/errors/error_422'

  mount StripeEvent::Engine => '/stripe'

  resources :projects do
    resources :activities
    resources :categories
    resources :members
    resources :invitations
    resources :todos do
      get 'planner', on: :collection
      post 'set_due_date'
    end
    resources :announcements
    resources :issues do
      resources :comments
    end
    resources :events
    get 'settings', :to => 'projects#get_settings', :controller => 'projects'
    post 'set_settings', :to => 'projects#set_settings', :controller => 'projects'
  end

  # devise_for :users
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'devise/sessions'}
  devise_scope :user do
    put 'update_card', :to => 'registrations#update_card', as: :update_card
  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end

  authenticated :user do
    root to: 'projects#index', as: :authenticated_root
  end


  #match '/users/:id', :to => 'users#show', :as => :user
  #match '/users/billing', :to => 'registrations#show', :as => :user
  #match '/projects/:project_id/:controller/:action(/:id)'
  get '/users/:id', :to => 'users#show', :as => :user_id
  get '/users/billing', :to => 'registrations#show', :as => :user_billing
  #get '/projects/:project_id/:controller/:action(/:id)'

  unless Rails.application.config.consider_all_requests_local
    #match '*not_found', to: 'errors#error_404'
    get '*not_found', to: 'errors#error_404'
  end

  #--- newer, more explicit routes in Rails 4
  put '/projects/:project_id/todos/mark_complete/:id' => 'todos#mark_complete'
  put '/projects/:project_id/todos/mark_incomplete/:id' => 'todos#mark_incomplete'
  post '/projects/:project_id/todos/sort' => 'todos#sort'
  put '/projects/:project_id/issues/mark_complete/:id' => 'issues#mark_complete'
  put '/projects/:project_id/issues/mark_incomplete/:id' => 'issues#mark_incomplete'
  post '/projects/:project_id/issues/sort' => 'issues#sort'

  put '/projects/:project_id/members/make_admin/:id' => 'members#make_admin'
  put '/projects/:project_id/members/remove_admin/:id' => 'members#remove_admin'
  put '/projects/:project_id/members/block/:id' => 'members#block'
  put '/projects/:project_id/members/unblock/:id' => 'members#unblock'

  get '/projects/:project_id/invitations/accept/:id' => 'invitations#accept'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

  audited :associated_with => :project

  validates_presence_of :subject

  belongs_to :project

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController


  load_and_authorize_resource :project
  load_and_authorize_resource :announcement, :through => :project


  def index
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @announcements = Announcement.where('project_id=?', params[:project_id])
    @announcements = @project.announcements
    @announcement = Announcement.new

    respond_to do |format|
      format.html # index2.html.erb
      format.json { render json: @announcements }
    end
  end


  def show
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announcement }
    end
  end


  def new
    # no longer needed, since authorization via CanCan loads these resources
    #@project = Project.find(params[:project_id])
    @announcement = Announcement.new
    @announcement.project_id = params[:project_id]
    @announcement.body=''

    # HACK: not sure why CanCan is allowing this, so here is a workaround...
    respond_to do |format|
      if can? :create, @project.announcements.build
        format.html # new.html.erb
        format.json { render json: @announcement }
      else
        flash[:error] = "You don't have permission to add a new announcement in this project."
        format.html { redirect_to project_announcements_path(@project) }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @announcement = Announcement.find(params[:id])
    @announcement.project_id = params[:project_id]
  end


  def create
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    @announcement = Announcement.new(announcement_params)
    @announcement.project_id = params[:project_id]

    # TODO: hack to overcome Ruby 1.9 date parse bug
    if params[:announcement][:expires_at].length > 0
      buffer = params[:announcement][:expires_at].split('/')  #we know the jQuery UI datepicker will return mm/dd/yyyy
      @announcement.expires_at = buffer[2] + '/' + buffer[0] + '/' + buffer[1]
    end

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to project_announcements_path(@project), notice: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @announcement = Announcement.find(params[:id])
    @announcement.update_attributes(announcement_params)

    # TODO: hack to overcome Ruby 1.9 date parse bug
    if params[:announcement][:expires_at].length > 0
      buffer = params[:announcement][:expires_at].split('/')  #we know the jQuery UI datepicker will return mm/dd/yyyy
      @announcement.expires_at = buffer[2] + '/' + buffer[0] + '/' + buffer[1]
    end

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to project_announcements_path(@project), notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to project_announcements_path(@project), notice: 'Announcement was successfully deleted.' }
      format.json { head :no_content }
    end
  end


  private


  def announcement_params
    params.require(:announcement).permit(:body, :expires_at, :member_id, :project_id, :subject)
  end


end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_for [@project, @announcement], :html => {:class => 'smart-form', :id => 'announcement_form'} do |f| %>

    <% if @announcement.errors.any? %>
        <div id="error_explanation" class='alert alert-error'>
          <button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button>
          <h4>Ooops, <%= pluralize(@announcement.errors.count, "error") %> prohibited this todo from being saved:</h4>

          <ul>
            <% @announcement.errors.full_announcements.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

    <% end %>

    <fieldset>

      <div class='row'>
        <section class="col col-6">
          <label class="label">Subject</label>
          <label class="input">
            <input class='input-lg' type="text" name="announcement[subject]" placeholder="Short subject for the announcement..." id='announcement_subject' value='<%= @announcement.subject %>'>
          </label>
        </section>

        <section class="col col-6">
          <label class="label">Expires On</label>
          <label class="input"> <i class="icon-append fa fa-calendar"></i>
            <input type="text" name="announcement[expires_at]" id="announcement_expires_at" placeholder="What date does this expire..." value='<%= @announcement.expires_at.strftime("%m/%d/%Y") unless @announcement.expires_at.nil? %>'>
          </label>
        </section>
      </div>

      <section>
        <label class="label">Body</label>
        <label class="textarea"><textarea rows="4" name="announcement[body]" id="announcement_body"><%= @announcement.body %></textarea> </label>
      </section>

    </fieldset>

    <footer>
      <button type="submit" class="btn btn-success pull-left">
        Save
      </button>
    </footer>

<% end %>

app/views/announcements/edit.html.erb
<div id="content">

  <!-- row -->
  <div class="row">

    <!-- col -->
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
      <h1 class="page-title txt-color-blueDark">

        <!-- PAGE HEADER -->
        <i class="fa-fw fa fa-bullhorn"></i>
        Edit Announcement

      </h1>
    </div>
    <!-- end col -->

  </div>
  <!-- end row -->


  <!-- widget grid -->
  <well>

    <!-- row -->

    <div class="row" style='background-color: #fff;'>

      <div class="widget-body">

        <%= render 'form' %>

      </div>

    </div>

    <!-- end row -->

  </well>
  <!-- end widget grid -->

</div>

<%= render :partial => '/projects/scripts' %>

<script type="text/javascript">

    $(document).ready(function () {

        pageSetUp();

        $('#announcement_subject').focus();

        $('#announcement_expires_at').datepicker({
            dateFormat : 'mm/dd/yy',
            prevText : '<i class="fa fa-chevron-left"></i>',
            nextText : '<i class="fa fa-chevron-right"></i>'
        });

        var $announcementForm = $("#announcement_form").validate({

            // Rules for form validation
            rules: {
                'announcement[subject]': {
                    required: true,
                    minlength: 3
                },
                'announcement[expires_at]': {
                    required: true
                }
            },

            // Announcements for form validation
            announcements: {
                'announcement[subject]': {
                    required: 'Please enter a short name for your announcement'
                },
                'announcement[expires_at]': {
                    required: 'Please enter a date for this announcement expiration'
                }
            },

            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });

    })

</script>

app/views/announcements/index.html.erb
<div class="row">

  <!-- col -->
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark">
      <!-- PAGE HEADER -->
      <i class="fa-fw fa fa-bullhorn"></i>
      Announcements
    </h1>
  </div>
  <!-- end col -->

  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-5 pull-right">
    <!-- Button trigger modal -->
    <% if can? :create, @project.announcements.build %>
        <%= link_to '<i class="fa fa-plus"></i> Create a new announcement'.html_safe, new_project_announcement_path(@project), :class => 'pull-right', :style=>'margin-right:22px; margin-top:10px;' %>
    <% end %>
  </div>

</div>

<div class="well">

  <% if @announcements.count == 0 %>
      None
  <% else %>


      <table id="inbox-table" class="table table-striped table-hover">
        <thead>
            <tr>
              <td>Announcement</td>
              <td>Created At</td>
              <td>Expires At</td>
            </tr>
        </thead>
        <tbody>

        <% @project.announcements.order('created_at desc').each do |announcement| %>

            <tr>

              <td class="inbox-data-announcement">
                <div>
                  <%= link_to announcement.subject, edit_project_announcement_path(@project, announcement) %>
                </div>
              </td>
              <td class="inbox-data-date hidden-xs" style='width:150px;'>
                <div>
                  <%= announcement.created_at.strftime("%m/%d/%Y %I:%M %P") %>
                </div>
              </td>
              <td class="inbox-data-date hidden-xs" style='width:150px;'>
                <div>
                  <%= announcement.expires_at.strftime("%m/%d/%Y") %>
                </div>
              </td>
            </tr>
        <% end %>


        </tbody>
      </table>

      <script>

          //Gets tooltips activated
          $("#inbox-table [rel=tooltip]").tooltip();

          $("#inbox-table input[type='checkbox']").change(function () {
              $(this).closest('tr').toggleClass("highlight", this.checked);
          });

          $("#inbox-table .inbox-data-announcement").click(function () {
              $this = $(this);
              getMail($this);
          })
          $("#inbox-table .inbox-data-from").click(function () {
              $this = $(this);
              getMail($this);
          })
          function getMail($this) {
              //console.log($this.closest("tr").attr("id"));
              loadURL("ajax/email-opened.html", $('#inbox-content > .table-wrap'));
          }


          $('.inbox-table-icon input:checkbox').click(function () {
              enableDeleteButton();
          })

          $(".deletebutton").click(function () {
              $('#inbox-table td input:checkbox:checked').parents("tr").rowslide();
              //$(".inbox-checkbox-triggered").removeClass('visible');
              //$("#compose-mail").show();
          });

          function enableDeleteButton() {
              var isChecked = $('.inbox-table-icon input:checkbox').is(':checked');

              if (isChecked) {
                  $(".inbox-checkbox-triggered").addClass('visible');
                  //$("#compose-mail").hide();
              } else {
                  $(".inbox-checkbox-triggered").removeClass('visible');
                  //$("#compose-mail").show();
              }
          }

      </script>

  <% end %>

</div>

<%= render :partial => '/projects/scripts' %>
<!-- Full Calendar -->
<script src="/SmartAdmin/js/plugin/fullcalendar/jquery.fullcalendar.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

        pageSetUp();

    });

</script>

app/views/announcements/new.html.erb
<div id="content">

  <!-- row -->
  <div class="row">

    <!-- col -->
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
      <h1 class="page-title txt-color-blueDark">

        <!-- PAGE HEADER -->
        <i class="fa-fw fa fa-bullhorn"></i>
        New Announcement

      </h1>
    </div>
    <!-- end col -->

  </div>
  <!-- end row -->


  <!-- widget grid -->
  <well>

    <!-- row -->

    <div class="row" style='background-color: #fff;'>

      <div class="widget-body">

        <%= render 'form' %>

      </div>

    </div>

    <!-- end row -->

  </well>
  <!-- end widget grid -->

</div>

<%= render :partial => '/projects/scripts' %>

<script type="text/javascript">

    $(document).ready(function () {

        pageSetUp();

        $('#announcement_subject').focus();

        $('#announcement_expires_at').datepicker({
            dateFormat : 'mm/dd/yy',
            prevText : '<i class="fa fa-chevron-left"></i>',
            nextText : '<i class="fa fa-chevron-right"></i>'
        });

        var $announcementForm = $("#announcement_form").validate({

            // Rules for form validation
            rules: {
                'announcement[subject]': {
                    required: true,
                    minlength: 3
                },
                'announcement[expires_at]': {
                    required: true
                }
            },

            // Announcements for form validation
            announcements: {
                'announcement[subject]': {
                    required: 'Please enter a short name for your announcement'
                },
                'announcement[expires_at]': {
                    required: 'Please enter a date for this announcement expiration'
                }
            },

            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });

    })

</script>