config/routes.rb
HuddleUp::Application.routes.draw do

  get 'home/index'
  get '/errors/error_404'
  get '/errors/error_500'
  get '/errors/error_422'

  mount StripeEvent::Engine => '/stripe'

  resources :projects do
    resources :activities
    resources :categories
    resources :members
    resources :invitations
    resources :todos do
      get 'planner', on: :collection
      post 'set_due_date'
    end
    resources :announcements
    resources :issues do
      resources :comments
    end
    resources :events
    get 'settings', :to => 'projects#get_settings', :controller => 'projects'
    post 'set_settings', :to => 'projects#set_settings', :controller => 'projects'
  end

  # devise_for :users
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'devise/sessions'}
  devise_scope :user do
    put 'update_card', :to => 'registrations#update_card', as: :update_card
  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end

  authenticated :user do
    root to: 'projects#index', as: :authenticated_root
  end


  #match '/users/:id', :to => 'users#show', :as => :user
  #match '/users/billing', :to => 'registrations#show', :as => :user
  #match '/projects/:project_id/:controller/:action(/:id)'
  get '/users/:id', :to => 'users#show', :as => :user_id
  get '/users/billing', :to => 'registrations#show', :as => :user_billing
  #get '/projects/:project_id/:controller/:action(/:id)'

  unless Rails.application.config.consider_all_requests_local
    #match '*not_found', to: 'errors#error_404'
    get '*not_found', to: 'errors#error_404'
  end

  #--- newer, more explicit routes in Rails 4
  put '/projects/:project_id/todos/mark_complete/:id' => 'todos#mark_complete'
  put '/projects/:project_id/todos/mark_incomplete/:id' => 'todos#mark_incomplete'
  post '/projects/:project_id/todos/sort' => 'todos#sort'
  put '/projects/:project_id/issues/mark_complete/:id' => 'issues#mark_complete'
  put '/projects/:project_id/issues/mark_incomplete/:id' => 'issues#mark_incomplete'
  post '/projects/:project_id/issues/sort' => 'issues#sort'

  put '/projects/:project_id/members/make_admin/:id' => 'members#make_admin'
  put '/projects/:project_id/members/remove_admin/:id' => 'members#remove_admin'
  put '/projects/:project_id/members/block/:id' => 'members#block'
  put '/projects/:project_id/members/unblock/:id' => 'members#unblock'

  get '/projects/:project_id/invitations/accept/:id' => 'invitations#accept'

end

app/models/event.rb
class Event < ActiveRecord::Base

  audited :associated_with => :project

  belongs_to :project

  validates_presence_of :title
  validates_presence_of :start_date

  validate :date_logic_is_ok,
           :time_logic_is_ok


  def date_logic_is_ok
    if self.end_date.nil?
      self.all_day = true
      return
    end

    if self.end_date < self.start_date
      errors.add(:end, "can't be less than the start date.")
    end
  end


  def time_logic_is_ok
    if end_time.nil?
      self.all_day = true
      return
    end

    if start_time.nil?
      self.all_day = true
      return
    end

    if end_time < start_time
      errors.add(:end_time, "can't be less than the start time.")
    end
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  load_and_authorize_resource :project
  load_and_authorize_resource :event, :through => :project


  def index
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @events = Event.where('project_id=?', params[:project_id]).order('event_date')
    @events = @project.events.order('start_date')

    respond_to do |format|
      format.html # index2.html.erb
      format.json { render json: @events }
    end
  end


  def show
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @event = Event.find(params[:id])
    @member = Member.where('user_id=?', current_user.id).where('project_id=?', @project.id).first()

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end


  def new
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    @event = Event.new
    @event.start_date = Date.today
    @event.end_date = Date.today
    @event.project_id = params[:project_id]
    @event.class_name='bg-color-blue txt-color-white'
    @event.icon='fa-warning'
    @event.start_time=nil
    @event.end_time=nil
    @event.all_day=false

    # HACK: not sure why CanCan is allowing this, so here is a workaround...
    respond_to do |format|
      if can? :create, @project.events.build
        format.html # new.html.erb
        format.json { render json: @todo }
      else
        flash[:error] = "You don't have permission to add a new event to this project."
        format.html { redirect_to project_events_path(@project) }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def edit
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @event = Event.find(params[:id])
    @event.project_id = params[:project_id]
  end


  def create
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    @event = Event.new(event_params)
    @event.project_id = params[:project_id]

    # correct date format
    begin
      if params[:event][:start_date].length > 0  # != ''
        @event.start_date = Date.strptime(params[:event][:start_date], '%m/%d/%Y')
      else
        @event.start_date = nil
      end
    rescue Exception=>e
      Rails.logger.error(e.to_s)
      @event.errors.add e.to_s
    end

    # correct date format
    begin
      if params[:event][:end_date].length > 0  # != ''
        @event.end_date = Date.strptime(params[:event][:end_date], '%m/%d/%Y')
      else
        @event.end_date = nil
      end
    rescue Exception=>e
      Rails.logger.error(e.to_s)
      @event.errors.add e.to_s
    end

    respond_to do |format|
      if @event.save
        format.html { redirect_to project_events_path(@project), notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @event = Event.find(params[:id])
    @event.update_attributes(event_params)
    @event.all_day = !params[:event]['all_day'].nil?

    if params[:event][:start_date].length == 0
      @event.errors.add(:start_date, 'Start Date is not valid.')
    else
      # TODO: hack to overcome Ruby 1.9 date parse bug
      buffer = params[:event][:start_date].split('/')  #we know the jQuery UI datepicker will return mm/dd/yyyy
      @event.start_date = buffer[2] + '/' + buffer[0] + '/' + buffer[1]
    end

    if !(params[:event][:end_date].length == 0)
      # TODO: hack to overcome Ruby 1.9 date parse bug
      buffer = params[:event][:end_date].split('/')  #we know the jQuery UI datepicker will return mm/dd/yyyy
      @event.end_date = buffer[2] + '/' + buffer[0] + '/' + buffer[1]
    end

    respond_to do |format|
      if @event.save
        format.html { redirect_to project_events_path(@project), notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:project_id])
    # @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to project_events_path(@project), notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end


  private


  def event_params
    params.require(:event).permit(:project_id, :title, :start_date, :end_date, :all_day, :class_name, :icon, :description, :start_time, :end_time)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="row">

  <!-- col -->
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-6">
    <h1 class="page-title txt-color-blueDark">
      <!-- PAGE HEADER -->
      <i class="fa-fw fa fa-calendar"></i>
      Calendar of Events and Milestones
    </h1>
  </div>
  <!-- end col -->

  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-5 pull-right">
    <!-- Button trigger modal -->
    <% if can? :create, @project.events.build %>
        <%= link_to '<i class="fa fa-plus"></i> Create a new event'.html_safe, new_project_event_path(@project), :class => 'pull-right', :style=>'margin-right:22px; margin-top:10px;' %>
    <% end %>
  </div>

</div>


<div class="row">


  <div class="col-sm-12 col-md-12 col-lg-12">

    <div class="btn-group">
      <button class="btn dropdown-toggle btn-default" data-toggle="dropdown" id="viewChooser">
        Show: <span id="viewRange"></span> <i class="fa fa-caret-down"></i>
      </button>
      <ul class="dropdown-menu js-status-update pull-right">
        <li>
          <a href="javascript:void(0);" id="mt">Month</a>
        </li>
        <li>
          <a href="javascript:void(0);" id="ag">Week</a>
        </li>
        <li>
          <a href="javascript:void(0);" id="td">Today</a>
        </li>
      </ul>
    </div>

      <div id="calendar-buttons" class="pull-right">

        <div class="btn-group">
          <a href="javascript:void(0)" class="btn btn-default btn-xs" id="btn-prev"><i class="fa fa-chevron-left"></i></a>
          <a href="javascript:void(0)" class="btn btn-default btn-xs" id="btn-next"><i class="fa fa-chevron-right"></i></a>
        </div>
      </div>




    <div id="calendar"></div>

  </div>

</div>

<%= render :partial => '/projects/scripts' %>
<!-- Full Calendar -->
<script src="/SmartAdmin/js/plugin/fullcalendar/jquery.fullcalendar.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

        pageSetUp();

        "use strict";

        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();

        var hdr = {
            left: 'title',
            center: 'month,agendaWeek,agendaDay',
            right: 'prev,today,next'
        };

        var calendarViewName = $.cookie('calendarView');
        if (calendarViewName == null)
            calendarViewName = 'agendaWeek';
        //console.log('calendarViewName=' + calendarViewName);

        /* initialize the calendar
         -----------------------------------------------------------------*/

        $('#calendar').fullCalendar({

            header: hdr,
            buttonText: {
                prev: '<i class="fa fa-chevron-left"></i>',
                next: '<i class="fa fa-chevron-right"></i>'
            },

            defaultView: calendarViewName,
            viewDisplay: function( view )
            {
                //save your cookie here, it's triggered each time the view changes
                //console.log('changing view name to... ');
                //console.log(view.name);
                $.cookie('calendarView', view.name);
            },

            events: [
                <% @events.each do |m| %>
                {"all_day":<%= m.all_day? %>,
                    "id":<%= m.id %>,
                    "project_id":<%= m.project_id %>,
                    "start": new Date(<%= m.start_date.strftime("%Y") %>, <%= m.start_date.strftime("%m") %>-1, <%= m.start_date.strftime("%d") %>
                            <%= ", " + m.start_time.strftime("%H,%M") unless m.start_time.nil? %>  ),

                    <% if !m.end_date.nil? %>
                    "end": new Date(<%= m.end_date.strftime("%Y") %>, <%= m.end_date.strftime("%m") %>-1, <%= m.end_date.strftime("%d") %>
                            <%= ", " + m.end_time.strftime("%H,%M") unless m.end_time.nil? %>  ),
                    <% end %>

                    'allDay':<%= m.all_day? %>,
                    "title": "<%= m.title %>",
                    "description": "<%= m.description %>",
                    "className":"<%= m.class_name %>",
                    "icon": "<%= m.icon %>"},
                <% end %>
            ],

            eventRender: function (event, element, icon) {
                if (!event.description == "") {
                    element.find('.fc-event-title').append("<br/><span class='ultra-light'>" + event.description +
                            "</span>");
                }
                if (!event.icon == "") {
                    element.find('.fc-event-title').append("<i class='air air-top-right fa " + event.icon +
                            " '></i>");
                }
            },

            eventClick: function (event) {
                // opens events in a popup window
                // alert(event.id);
                window.location.href = '/projects/<%= @project.id %>/events/' + event.id + '/edit';
                return false;
            },

            windowResize: function (event, ui) {
                $('#calendar').fullCalendar('render');
            }
        });

        /* hide default buttons */
        $('.fc-header-right, .fc-header-center').hide();


        $('#calendar-buttons #btn-prev').click(function () {
            $('.fc-button-prev').click();
            return false;
        });

        $('#calendar-buttons #btn-next').click(function () {
            $('.fc-button-next').click();
            return false;
        });

        $('#calendar-buttons #btn-today').click(function () {
            $('.fc-button-today').click();
            return false;
        });

        $('#viewRange').text('Week');
        $('#mt').click(function () {
            $('#calendar').fullCalendar('changeView', 'month');
            $('#viewRange').text('Month');
        });

        $('#ag').click(function () {
            $('#calendar').fullCalendar('changeView', 'agendaWeek');
            $('#viewRange').text('Week');
        });

        $('#td').click(function () {
            $('#calendar').fullCalendar('changeView', 'agendaDay');
            $('#viewRange').text('Week');
        });


    });

</script>

app/views/events/new.html.erb
<div id="content">

  <!-- row -->
  <div class="row">

    <!-- col -->
    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
      <h1 class="page-title txt-color-blueDark">

        <!-- PAGE HEADER -->
        <i class="fa-fw fa fa-calendar"></i>
        New Event

      </h1>
    </div>
    <!-- end col -->

  </div>
  <!-- end row -->


  <!-- widget grid -->
  <well>

    <!-- row -->

    <div class="row" style='background-color: #fff;'>

      <div class="widget-body">

        <%= render 'form' %>

      </div>

    </div>

    <!-- end row -->

  </well>
  <!-- end widget grid -->

</div>

<%= render :partial => '/projects/scripts' %>
<script src="/SmartAdmin/js/plugin/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {

        pageSetUp();

        $('#event_start_date').datepicker({
            dateFormat : 'mm/dd/yy',
            prevText : '<i class="fa fa-chevron-left"></i>',
            nextText : '<i class="fa fa-chevron-right"></i>'
        });

        $('#event_end_date').datepicker({
            dateFormat : 'mm/dd/yy',
            prevText : '<i class="fa fa-chevron-left"></i>',
            nextText : '<i class="fa fa-chevron-right"></i>'
        });

        $('#event_start_time').timepicker();
        $('#event_end_time').timepicker();

        $('#event_start_time').val('');
        $('#event_end_time').val('');

        $('#event_title').focus();

        //--- build up the validation suite for this calendar event


        jQuery.validator.addMethod("EndDateCannotBeLessThanStartDate", function(value, element) {
            if ($('#event_end_date').val() != '')
            {
                var startDt = new Date($('#event_start_date').val());
                var endDt = new Date($('#event_end_date').val());

                if(startDt <= endDt)
                {
                    return true;
                } else {
                    return false;
                }
            }
            else {
                return true;
            }
        }, "End date cannot be less than start date");


        jQuery.validator.addMethod("BothTimesMustBeEntered", function(value, element) {
            if ($('#event_start_time').val() != '')
                if ($('#event_end_time').val() == '')
                    return false;
            if ($('#event_end_time').val() != '')
                if ($('#event_start_time').val() == '')
                    return false;
            return true;
        }, "Both times must be entered when one or the other is present");


        jQuery.validator.addMethod("EndTimeCannotBeLessThanStartTime", function(value, element) {

            var startDate = $('#event_start_date').val();
            var endDate = $('#event_end_date').val();
            var startTime = new Date(($('#event_start_date').val() + ' ' + $('#event_start_time').val()));
            var endTime = new Date(($('#event_end_date').val() + ' ' + $('#event_end_time').val()));

            if (endDate == startDate)
            {
                if(startTime <= endTime)
                {
                    return true;
                } else {
                    return false;
                }
            }
            else {
                return true;
            }
        }, "End time cannot be less than start time");


        var $eventForm = $("#event_form").validate({

            // Rules for form validation
            rules: {
                'event[title]': {
                    required: true,
                    minlength: 3
                },
                'event[start_date]': {
                    required: true
                },
                'event[end_date]': {
                    EndDateCannotBeLessThanStartDate: true
                },
                'event[end_time]': {
                    EndTimeCannotBeLessThanStartTime: true,
                    BothTimesMustBeEntered: true
                },
                'event[start_time]': {
                    EndTimeCannotBeLessThanStartTime: true,
                    BothTimesMustBeEntered: true
                }
            },

            // Messages for form validation
            messages: {
                'event[title]': {
                    required: 'Please enter a short name for your event'
                },
                'event[start_date]': {
                    required: 'Please enter at least a starting date for your event'
                }
            },

            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });


        //--- field change event handlers


        $('#event_title').change(function() {
            //re-validate the form
            var validator = $( "#event_form" ).validate();
            validator.form();
        });

        $('#event_start_date').change(function() {
            //re-validate the form
            var validator = $( "#event_form" ).validate();
            validator.form();
        });

        $('#event_end_date').change(function() {
            //re-validate the form
            var validator = $( "#event_form" ).validate();
            validator.form();
        });

        $('#event_start_time').change(function() {
            //re-validate the form
            var validator = $( "#event_form" ).validate();
            validator.form();
        });

        $('#event_end_time').change(function() {
            //re-validate the form
            var validator = $( "#event_form" ).validate();
            validator.form();
        });

        $('#event_all_day').change(function() {

            if (userDefinedAllDay)
                userDefinedAllDay = false;
            else
                userDefinedAllDay = true;

            //remove the time(s) if unchecked
            if (userDefinedAllDay)
            {
                userDefinedStartTime = $('#event_start_time').val();
                userDefinedEndTime = $('#event_end_time').val();
                $('#event_start_time').val("");
                $('#event_end_time').val("");
            }
            else
            {
                $('#event_start_time').val(userDefinedStartTime);
                $('#event_end_time').val(userDefinedEndTime);
            }

            //re-validate the form
            var validator = $( "#event_form" ).validate();
            validator.form();
        });

    })

</script>

app/views/events/show.html.erb
<div class="navbar">

  <script type="text/javascript">
      try {
          ace.settings.check('navbar', 'fixed')
      } catch (e) {
      }
  </script>

  <div class="navbar-inner">
    <div class="container-fluid">

      <a class="brand" href="#">
        <small><i class="icon-check"></i> HuddleUp - <%= @project.name %></small>
      </a>

      <%= render :partial => '/projects/top_nav', :locals => {:post => 'foo'} %>

    </div>
    <!--/.container-fluid-->
  </div>
  <!--/.navbar-inner-->

</div>


<div class="main-container container-fluid">
  <a class="menu-toggler" id="menu-toggler" href="#">
    <span class="menu-text"></span>
  </a>

  <%= render :partial => '/projects/side_nav_1', :locals => {:component => 'events', :project_id => @project.id} %>

  <div class="main-content">


    <% crumbs = [['Projects', projects_path],
                 [@project.name, project_path(@project)],
                 ['Events', project_events_path(@project)]] %>

    <%= render :partial => '/projects/breadcrumbs', :locals => {:crumbs => crumbs, :title => @event.subject} %>

    <div class="page-content">
      <div class="page-header position-relative">
        <h1>
          <i class="icon-calendar"></i> <%= @event.subject %>
          <small>
            <i class='icon-double-angle-right'></i>
            <a href="/projects/<%= @project.id %>/events/<%= @event.id %>/edit">Edit this event's definition</a>
          </small>
        </h1>

      </div>
      <!--/.page-header-->

      <div class="row-fluid">
        <div class="span12">
          <!--PAGE CONTENT BEGINS-->

          <div class="span5">
            <div class="widget-box">
              <div class="widget-header widget-header-large">
                <h4>Event Details</h4>
              </div>

              <div class="widget-body">
                <div class="widget-main">
                  <div class="alert alert-info">
                    <table>
                      <tr>
                        <td style='width:33%; padding-bottom: 20px;'>Millestone Name:</td>
                        <td style='width:67%; padding-bottom: 20px;'><%= @event.subject %></td>
                      </tr>
                      <tr>
                        <td style='padding-bottom: 20px;'>Date:</td>
                        <td style='padding-bottom: 20px;'><%= @event.event_date.strftime('%m/%d/%Y') %></td>
                      </tr>
                      <tr>
                        <td style='padding-bottom: 20px;'>Progress:</td>
                        <td style='padding-bottom: 20px;'>say what?</td>
                      </tr>
                      <tr>
                        <td style='padding-bottom: 20px;'>Size:</td>
                        <td style='padding-bottom: 20px;'></td>
                      </tr>
                      <tr>
                        <td>Calculated:</td>
                        <td></td>
                      </tr>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="span7">
            <div class="widget-box ">
              <div class="widget-header widget-header-large">
                <h4 class="lighter smaller"> Associated Tasks</h4>

              </div>

              <div class="widget-body">
                <div class="widget-main padding-5">
                  <div class="tab-content padding-8">
                    <div id="events-gadget" class="tab-pane active">

                      <% if flash[:notice] %>
                          <div class='alert alert-block alert-success'>
                            <button type="button" class="close" data-dismiss="alert">
                              <i class="icon-remove"></i></button>
                            <strong><i class="icon-ok"></i> <%= flash[:notice] %></strong>
                          </div>
                      <% end %>

                      <div id="tasks-tab" class="tab-pane active">
                      </div>
                    </div>
                  </div>
                </div>
              </div>


            </div>


            <div id="modal-add-form" class="modal hide" tabindex="-1">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="blue bigger">Add a new task</h4>
              </div>

              <div class="modal-footer">
                <button class="btn btn-small" data-dismiss="modal">
                  <i class="icon-remove"></i>
                  Cancel
                </button>

                <button class="btn btn-small btn-primary" onclick="javascript:$('#new_task').submit();">
                  <i class="icon-ok"></i>
                  Save
                </button>
              </div>
            </div>

            <!-- END -->

          </div>

        </div>
        <!--/row-->

        <!--PAGE CONTENT ENDS-->
      </div>
      <!--/.span-->
    </div>
    <!--/.row-fluid-->
  </div>
  <!--/.page-content-->

  <div class="ace-settings-container" id="ace-settings-container">
    <div class="btn btn-app btn-mini btn-warning ace-settings-btn" id="ace-settings-btn">
      <i class="icon-cog bigger-150"></i>
    </div>

    <div class="ace-settings-box" id="ace-settings-box">
      <div>
        <div class="pull-left">
          <select id="skin-colorpicker" class="hide">
            <option data-skin="default" value="#438EB9">#438EB9</option>
            <option data-skin="skin-1" value="#222A2D">#222A2D</option>
            <option data-skin="skin-2" value="#C6487E">#C6487E</option>
            <option data-skin="skin-3" value="#D0D0D0">#D0D0D0</option>
          </select>
        </div>
        <span>&nbsp; Choose Skin</span>
      </div>

      <div>
        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-navbar"/>
        <label class="lbl" for="ace-settings-navbar"> Fixed Navbar</label>
      </div>

      <div>
        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-sidebar"/>
        <label class="lbl" for="ace-settings-sidebar"> Fixed Sidebar</label>
      </div>

      <div>
        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-breadcrumbs"/>
        <label class="lbl" for="ace-settings-breadcrumbs"> Fixed Breadcrumbs</label>
      </div>

      <div>
        <input type="checkbox" class="ace ace-checkbox-2" id="ace-settings-rtl"/>
        <label class="lbl" for="ace-settings-rtl"> Right To Left (rtl)</label>
      </div>
    </div>
  </div>
  <!--/#ace-settings-container-->
</div><!--/.main-content-->
</div><!--/.main-container-->

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-small btn-inverse">
  <i class="icon-double-angle-up icon-only bigger-110"></i>
</a>

<!-- inline scripts related to this page -->
<script type="text/javascript" src="/assets/js/spin.min.js"></script>
<script src="/assets/js/date-time/bootstrap-datepicker.min.js"></script>
<script type="text/javascript">

    $(function () {

        $('.date-picker').datepicker();

        var $tooltip = $("<div class='tooltip top in' style='display:none;'><div class='tooltip-inner'></div></div>").appendTo('body');
        $('[data-rel="tooltip"]').tooltip();

        $('#modal-add-form').on('shown', function() {
            console.log('#modal-add-form is shown...')
            $(this).find($('#task_subject')).focus();
        });


        $('#tasks').sortable({
            axis: 'y',
            items: 'li',
            update: function () {
                $.ajax({
                    type: 'post',
                    data: $('#tasks').sortable('serialize'),
                    dataType: 'script',
                    complete: function (request) {
                        //$('#tasks').effect('highlight');
                    },
                    url: '/projects/<%= @project.id %>/events/<%= @event.id %>/tasks/sort'})
            }
        });

        $('#tasks').disableSelection();

        var opts = {
            lines: 13, // The number of lines to draw
            length: 20, // The length of each line
            width: 10, // The line thickness
            radius: 30, // The radius of the inner circle
            corners: 1, // Corner roundness (0..1)
            rotate: 0, // The rotation offset
            direction: 1, // 1: clockwise, -1: counterclockwise
            color: '#000', // #rgb or #rrggbb
            speed: 1, // Rounds per second
            trail: 60, // Afterglow percentage
            shadow: false, // Whether to render a shadow
            hwaccel: false, // Whether to use hardware acceleration
            className: 'spinner', // The CSS class to assign to the spinner
            zIndex: 2e9, // The z-index (defaults to 2000000000)
            top: 'auto', // Top position relative to parent in px
            left: 'auto' // Left position relative to parent in px
        };

        $('#tasks input:checkbox').removeAttr('checked').on('click', function () {
            var target = document.getElementById('tasks');
            var spinner = new Spinner(opts).spin(target);

            var id = $(this).closest('li').attr('data-pk');
            var done = ($(this).closest('li').attr('data-completed') == "true");
            if (done)
            {
                //alert('marking incomplete');
                window.location.href='/projects/<%= @project.id %>/events/<%= @event.id %>/tasks/mark_incomplete/' + id;
            }
            else
            {
                //alert('marking complete');
                window.location.href='/projects/<%= @project.id %>/events/<%= @event.id %>/tasks/mark_complete/' + id;
            }
        });

        $('.task').each(function () {
            var done = ($(this).attr('data-completed') == "true");
            var pk = $(this).attr('data-pk');
            if (done) {
                $(this).addClass('selected');
                $('#chk_' + pk).attr('checked', true);  //WORKS!
                //$(this).find('input:checkbox').attr('checked', true);
            }
        });

    });


</script>