config/routes.rb
HuddleUp::Application.routes.draw do

  get 'home/index'
  get '/errors/error_404'
  get '/errors/error_500'
  get '/errors/error_422'

  mount StripeEvent::Engine => '/stripe'

  resources :projects do
    resources :activities
    resources :categories
    resources :members
    resources :invitations
    resources :todos do
      get 'planner', on: :collection
      post 'set_due_date'
    end
    resources :announcements
    resources :issues do
      resources :comments
    end
    resources :events
    get 'settings', :to => 'projects#get_settings', :controller => 'projects'
    post 'set_settings', :to => 'projects#set_settings', :controller => 'projects'
  end

  # devise_for :users
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'devise/sessions'}
  devise_scope :user do
    put 'update_card', :to => 'registrations#update_card', as: :update_card
  end

  unauthenticated do
    root to: 'home#index', as: :unauthenticated_root
  end

  authenticated :user do
    root to: 'projects#index', as: :authenticated_root
  end


  #match '/users/:id', :to => 'users#show', :as => :user
  #match '/users/billing', :to => 'registrations#show', :as => :user
  #match '/projects/:project_id/:controller/:action(/:id)'
  get '/users/:id', :to => 'users#show', :as => :user_id
  get '/users/billing', :to => 'registrations#show', :as => :user_billing
  #get '/projects/:project_id/:controller/:action(/:id)'

  unless Rails.application.config.consider_all_requests_local
    #match '*not_found', to: 'errors#error_404'
    get '*not_found', to: 'errors#error_404'
  end

  #--- newer, more explicit routes in Rails 4
  put '/projects/:project_id/todos/mark_complete/:id' => 'todos#mark_complete'
  put '/projects/:project_id/todos/mark_incomplete/:id' => 'todos#mark_incomplete'
  post '/projects/:project_id/todos/sort' => 'todos#sort'
  put '/projects/:project_id/issues/mark_complete/:id' => 'issues#mark_complete'
  put '/projects/:project_id/issues/mark_incomplete/:id' => 'issues#mark_incomplete'
  post '/projects/:project_id/issues/sort' => 'issues#sort'

  put '/projects/:project_id/members/make_admin/:id' => 'members#make_admin'
  put '/projects/:project_id/members/remove_admin/:id' => 'members#remove_admin'
  put '/projects/:project_id/members/block/:id' => 'members#block'
  put '/projects/:project_id/members/unblock/:id' => 'members#unblock'

  get '/projects/:project_id/invitations/accept/:id' => 'invitations#accept'

end

app/models/project.rb
class Project < ActiveRecord::Base

  include ActionView::Helpers::DateHelper

  has_settings do |s|
    s.key :create_milestone_for_todo_with_due_date, :defaults => { :configured_value => false }
    s.key :create_todo_for_event_entry,             :defaults => { :configured_value => true }
    s.key :email_members_when_new_alert,            :defaults => { :configured_value => true }
  end

  after_create :create_disqus_token
  after_create :set_initial_settings

  audited
  has_associated_audits

  validates_presence_of :name

  #belongs_to :user
  has_many :members, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :todos, :dependent => :destroy
  has_many :issues, :dependent => :destroy
  has_many :announcements, :dependent => :destroy
  has_many :categories, :dependent => :destroy


  def set_initial_settings
    self.settings(:create_milestone_for_todo_with_due_date).configured_value = false
    self.settings(:create_todo_for_event_entry).configured_value = false
    self.settings(:email_members_when_new_alert).configured_value = false
  end


  def get_last_updated_by
    #last_updated = Audit.where('(auditable_type=? and auditable_id=?) or (associated_type=? and associated_id=?)', 'Project', id, 'Project', id).order('created_at desc').first

    sql = "select * from audits where (auditable_type='Project' and auditable_id=" + id.to_s + ") union select * from audits where (associated_type='Project' and associated_id=" + id.to_s + ") order by created_at desc limit 1"
    last_updated = Audit.find_by_sql(sql).first()

    if last_updated.nil?
      return ""
    end

    who = User.find(last_updated.user_id).name
    return who + ', ' + time_ago_in_words(last_updated.created_at) + ' ago'
  end


  def how_many_todos_left
    return todos.where('is_complete != true or is_complete is null').count
    #return Todo.where('project_id=?', id).where('is_complete is NULL').count
  end


  def how_many_issues_left
    return issues.where('is_resolved != true or is_resolved is null').count
  end


  def how_many_todos_left_for_this_member(current_user_id)
    current_membership_id = determine_current_membership(current_user_id)
    return todos.where('is_complete != true or is_complete is null').where('member_id=?', current_membership_id).count
  end


  def how_many_issues_left_for_this_member(current_user_id)
    current_membership_id = determine_current_membership(current_user_id)
    return issues.where('is_resolved != true or is_resolved is null').where('member_id=?', current_membership_id).count
  end


  def determine_current_membership(current_user_id)
    current_membership_id = Member.where('user_id=?', current_user_id).where('project_id=?', id).first().id
    return current_membership_id
  end


  def current_user_is_project_admin?(current_user_id)
    current_membership = Member.where('user_id=?', current_user_id).where('project_id=?', id).first()
    return current_membership.is_admin?
  end


  #def how_many_unread_messages_for_this_member(current_user_id)
  #  current_membership_id = determine_current_membership(current_user_id)
  #  messages_current_user_has_read = 0
  #  messages.each do |m|
  #    if m.read_receipts.where('member_id=?', current_membership_id).count > 0
  #      messages_current_user_has_read += 1
  #    end
  #  end
  #
  #  badge_number_for_user = messages.count - messages_current_user_has_read
  #  return badge_number_for_user
  #end


  def how_many_active_announcements
    return announcements.where('expires_at >= ?', Date.today).count
  end


  def how_many_events_left
    return events.where('start_date>=?', Date.today).count
  end


  def create_disqus_token
    update_attributes!(:token_for_disqus => SecureRandom.hex)
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController


  load_and_authorize_resource :except=>:index


  def index
    # no longer needed, since authorization via CanCan loads these resources
    @membership = Member.where('user_id=' + current_user.id.to_s).where("status_code <> '9'").pluck(:project_id)

    if @membership.count == 0
      @projects = []
    else
      @projects = Project.where('id in (?)', @membership).order('status_code')
    end

    respond_to do |format|
      format.html # index2.html.erb
      format.json { render json: @projects }
    end
  end


  def show
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:id])
    @member = @project.members.where('user_id=?', current_user.id).first
    @late_todos = @project.todos.where('is_complete is null').where('due_date < ?', Date.today)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end


  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end


  def edit
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:id])
  end


  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        @project.members.create(:user_id => current_user.id, :is_admin => true, :joined_date => Time.now, :status_code=>1 )
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy

    # no longer needed, since authorization via CanCan loads these resources
    # @project = Project.find(params[:id])

    respond_to do |format|
      if @project.destroy
        format.html { redirect_to projects_path, notice: 'Project was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @project, :alert => @projects.errors.first.message }
        format.json { head :no_content }
      end
    end
  end


  def get_settings
    @project = Project.find(params[:project_id])
    @category = Category.new

    respond_to do |format|
      format.html
      format.json { render json: @projects }
    end
  end


  def set_settings
    @project = Project.find(params[:project_id])

    # user.settings(:dashboard).theme = 'black'
    @project.settings(:create_milestone_for_todo_with_due_date).configured_value = !params['setting_01'].nil?
    @project.settings(:create_todo_for_event_entry).configured_value = !params['setting_02'].nil?
    @project.settings(:email_members_when_new_alert).configured_value = !params['setting_03'].nil?
    @project.save!

    flash[:notice] = 'Settings were successfully updated.'
    redirect_to project_path (@project)

  end


  private


  def project_params
    params.require(:project).permit(:description, :name, :status_code) #, :token_for_disqus, :is_complete)
  end


end

app/helpers/projects_helper.rb
module ProjectsHelper

  def get_project_status_color(p)

    status_color = ''

    if p.status_code == 1
      status_color = 'success'
    end
    if p.status_code == 2
      status_color = 'warning'
    end
    if p.status_code == 3
      status_color = 'danger'
    end
    if p.status_code == 4
      status_color = 'default'
    end
    if p.status_code == 5
      status_color = 'info'
    end

    return status_color
  end


  def get_project_status_text(p)

    status = ''

    if p.status_code == 0
      status = 'Not Started'
    end
    if p.status_code == 1
      status = 'On Track'
    end
    if p.status_code == 2
      status = 'Warning'
    end
    if p.status_code == 3
      status = 'In Trouble'
    end
    if p.status_code == 4
      status = 'Paused'
    end
    if p.status_code == 5
      status = 'Complete'
    end

    return status
  end


end

app/views/projects/_breadcrumbs.html.erb
<ol class="breadcrumb">
  <% if current_user %>
      <li><%= link_to current_user.name, '/user/edit' %></li>
      <li><%= link_to 'My Projects', '/projects' %></li>
      <% if !@project.nil? && !@project.id.nil? %>

          <li><%= link_to @project.name, project_path(@project) %></li>

          <% if controller_name == 'todos' && !request.path.end_with?('planner') %>
              <li><%= link_to 'Todos', project_todos_path(@project) %></li>
              <% if !@todo.id.nil? %>
                  <li><a href='/projects/<%= @project.id %>/todos/<%= @todo.id %>/edit'><%= @todo.subject %>x</a></li>
              <% end %>
              <% if action_name == 'new' %>
                  <li>New</li>
              <% end %>
          <% end %>

          <% if controller_name == 'todos' && request.path.end_with?('planner') %>
              <li><%= link_to 'Planner', planner_project_todos_path(@project) %></li>
          <% end %>

          <% if controller_name == 'milestones' %>
              <li><%= link_to 'Milestones', project_milestones_path(@project) %></li>
              <% if !@milestone.nil? %>
                  <li><a href='/projects/<%= @project.id %>/milestones/<%= @milestone.id %>/edit'><%= @milestone.title %></a></li>
              <% end %>
              <% if action_name == 'new' %>
                  <li>New</li>
              <% end %>
          <% end %>

          <% if controller_name == 'issues' %>
              <li><%= link_to 'Issues', project_issues_path(@project) %></li>
              <% if !@issue.nil? %>
                  <li><a href='/projects/<%= @project.id %>/issues/<%= @issue.id %>/edit'><%= @issue.subject %></a></li>
              <% end %>
              <% if action_name == 'new' %>
                  <li>New</li>
              <% end %>
          <% end %>

          <% if controller_name == 'members' %>
              <li><%= link_to 'Members', project_members_path(@project) %></li>
              <% if !@member.nil? %>
                  <li><a href='/projects/<%= @project.id %>/members/<%= @member.id %>/edit'><%= @member.name %></a></li>
              <% end %>
              <% if action_name == 'new' %>
                  <li>New</li>
              <% end %>
          <% end %>

          <% if controller_name == 'messages' %>
              <li><%= link_to 'Messages', project_messages_path(@project) %></li>
              <% if !@member.nil? %>
                  <li><a href='/projects/<%= @project.id %>/messages/<%= @message.id %>/edit'><%= @message.subject %></a></li>
              <% end %>
              <% if action_name == 'new' %>
                  <li>New</li>
              <% end %>
          <% end %>

          <% if controller_name == 'activities' %>
              <li><%= link_to 'Timeline', project_activities_path(@project) %></li>
          <% end %>

          <% if request.path.end_with?('settings') %>
              <li><%= link_to 'Settings', project_settings_path(@project) %></li>
          <% end %>

<% end %>
  <% end %>
</ol>

app/views/projects/_comments.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'HuddleUp'; // required: replace example with your forum shortname
    var disqus_identifier = '<%= project.token_for_disqus %>';
    var disqus_developer = <%= Rails.env == "production" ? '0' : '1' %> ;
    var disqus_title = '<%= project.name %>';
    var disqus_url = '<%= project_path(project, :only_path => false) %>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/projects/_form.html.erb
<%= form_for(@project, :html => {:class => 'smart-form', :id => 'project_form'}) do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation" class='alert alert-error'>
          <button type="button" class="close" data-dismiss="alert"><i class="icon-remove"></i></button>
          <h4>Ooops, <%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h4>

          <ul>
            <% @project.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>

    <% end %>


    <fieldset>
      <div class='row'>
        <section class="col col-6">
          <label class="label">Project Name</label>
          <label class="input">
            <input type="text" class='input-lg' name="project[name]" placeholder="Give your project a short title..." id='project_name' value='<%= @project.name %>'>
          </label>
        </section>

        <section class="col col-6">
          <label class="label">Status</label>
          <label class="select">
            <%= select('project', 'status_code', [['Not started', 0], ['On track', 1], ['Troubled', 2], ['Late', 3], ['Locked/paused', 4], ['Complete', 5]], {}) %>
          </label>
        </section>
      </div>

      <section>
        <label class="label">Description</label>
        <label class="textarea"><textarea rows="4" name="project[description]" id="project_description"><%= @project.description %></textarea>
        </label>
      </section>

    </fieldset>

    <footer>
      <button type="submit" class="btn btn-success">
        Save
      </button>
    </footer>

<% end %>

app/views/projects/_scripts.html.erb
<!-- PACE LOADER - turn this on if you want ajax loading to show (caution: uses lots of memory on iDevices)-->
<script data-pace-options='{ "restartOnRequestAfter": true }' src="/SmartAdmin/js/plugin/pace/pace.min.js"></script>

<!-- Link to Google CDN's jQuery + jQueryUI; fall back to local -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>
    if (!window.jQuery) {
        document.write('<script src="/SmartAdmin/js/libs/jquery-2.1.1.min.js"><\/script>');
    }
</script>

<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script>
    if (!window.jQuery.ui) {
        document.write('<script src="/SmartAdmin/js/libs/jquery-ui-1.10.3.min.js"><\/script>');
    }
</script>

<!-- IMPORTANT: APP CONFIG -->
<script src="/SmartAdmin/js/app.config.js"></script>

<!-- JS TOUCH : include this plugin for mobile drag / drop touch events-->
<script src="/SmartAdmin/js/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script>

<!-- BOOTSTRAP JS -->
<script src="/SmartAdmin/js/bootstrap/bootstrap.min.js"></script>

<!-- CUSTOM NOTIFICATION -->
<script src="/SmartAdmin/js/notification/SmartNotification.min.js"></script>

<!-- JARVIS WIDGETS -->
<script src="/SmartAdmin/js/smartwidgets/jarvis.widget.min.js"></script>

<!-- EASY PIE CHARTS -->
<script src="/SmartAdmin/js/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>

<!-- SPARKLINES -->
<script src="/SmartAdmin/js/plugin/sparkline/jquery.sparkline.min.js"></script>

<!-- JQUERY VALIDATE -->
<script src="/SmartAdmin/js/plugin/jquery-validate/jquery.validate.min.js"></script>

<!-- JQUERY MASKED INPUT -->
<script src="/SmartAdmin/js/plugin/masked-input/jquery.maskedinput.min.js"></script>

<!-- JQUERY SELECT2 INPUT -->
<script src="/SmartAdmin/js/plugin/select2/select2.min.js"></script>

<!-- JQUERY UI + Bootstrap Slider -->
<script src="/SmartAdmin/js/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>

<!-- browser msie issue fix -->
<script src="/SmartAdmin/js/plugin/msie-fix/jquery.mb.browser.min.js"></script>

<!-- FastClick: For mobile devices -->
<script src="/SmartAdmin/js/plugin/fastclick/fastclick.min.js"></script>

<!--[if IE 8]>

<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

<![endif]-->


<!-- MAIN APP JS FILE -->
<script src="/SmartAdmin/js/app.min.js"></script>

<script src="/SmartAdmin/js/plugin/jquery-cookie/jquery-cookie.js"></script>

<!-- ENHANCEMENT PLUGINS : NOT A REQUIREMENT -->
<!-- Voice command : plugin -->
<script src="/SmartAdmin/js/speech/voicecommand.min.js"></script>

<!-- SmartChat UI : plugin -->
<script src="/SmartAdmin/js/smart-chat-ui/smart.chat.ui.min.js"></script>
<script src="/SmartAdmin/js/smart-chat-ui/smart.chat.manager.min.js"></script>

<!-- PAGE RELATED PLUGIN(S) -->
<script src="/SmartAdmin/js/plugin/moment/moment.min.js"></script>
<script src="/SmartAdmin/js/plugin/fullcalendar/jquery.fullcalendar.min.js"></script>
<script src="/SmartAdmin/js/plugin/bootstrap-tags/bootstrap-tagsinput.js"></script>

<script src="/SmartAdmin/js/rails.js"></script>

app/views/projects/_side_nav.html.erb
<!-- #NAVIGATION -->
<!-- Left panel : Navigation area -->
<!-- Note: This width of the aside area can be adjusted through LESS variables -->
<aside id="left-panel">


  <!-- NAVIGATION : This navigation is also responsive -->
    <nav>
        <ul>
            <% if !@project.nil? && !@project.id.nil? %>
              <li <%= "class='active'".html_safe if controller_name == 'projects' %> >
                <a href="/projects/<%= @project.id %>" title="Summary"><i class="fa fa-lg fa-fw fa-bar-chart-o"></i>
                  <span class="menu-item-parent">Summary</span></a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'members' %> >
                <a href="/projects/<%= @project.id %>/members" title="Members"><i class="fa fa-lg fa-fw fa-group"></i>
                  <span class="menu-item-parent">Members</span>
                </a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'events' %> >
                <a href="/projects/<%= @project.id %>/events" title="Events"><i class="fa fa-lg fa-fw fa-calendar"></i>
                  <span class="menu-item-parent">Calendar</span>
                  <span class="badge pull-right inbox-badge bg-color-red"><%= @project.how_many_events_left unless @project.how_many_events_left == 0 %></span></a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'announcements' %> >
                <a href="/projects/<%= @project.id %>/announcements" title="announcements"><i class="fa fa-lg fa-fw fa-bullhorn"></i>
                  <span class="menu-item-parent">Announcements</span>
                  <span class="badge pull-right inbox-badge bg-color-red"><%= @project.how_many_active_announcements unless @project.how_many_active_announcements == 0 %></span></a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'todos' && request.path.end_with?('planner') %> >
                <a href="/projects/<%= @project.id %>/todos/planner" title="Planner"><i class="fa fa-lg fa-fw fa-calendar-o"></i>
                  <span class="menu-item-parent">Planner</span>
                  </a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'todos' && !request.path.end_with?('planner') %> >
                <a href="/projects/<%= @project.id %>/todos" title="Todos"><i class="fa fa-lg fa-fw fa-check-square-o"></i>
                  <span class="menu-item-parent">Todos</span>
                  <span class="badge pull-right inbox-badge bg-color-red" id='badgeTodosCount'><%= @project.how_many_todos_left unless @project.how_many_todos_left == 0 %></span></a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'issues' %> >
                <a href="/projects/<%= @project.id %>/issues" title="Milestones"><i class="fa fa-lg fa-fw fa-bug"></i>
                  <span class="menu-item-parent">Issues</span>
                  <span class="badge pull-right inbox-badge bg-color-red" id="badgeIssuesCount"><%= @project.how_many_issues_left unless @project.how_many_issues_left == 0 %></span></a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'alerts' %> >
                <a href="/projects/<%= @project.id %>/alerts" title="Alerts"><i class="fa fa-lg fa-fw fa-bell"></i>
                  <span class="menu-item-parent">Alerts</span>
                </a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'activities' %> >
                <a href="/projects/<%= @project.id %>/activities" title="Alerts"><i class="fa fa-lg fa-fw fa-reorder"></i>
                  <span class="menu-item-parent">Timeline</span>
                </a>
              </li>

              <li <%= "class='active'".html_safe if controller_name == 'settings' %> >
                <a href="/projects/<%= @project.id %>/settings" title="Alerts"><i class="fa fa-lg fa-fw fa-cog"></i>
                  <span class="menu-item-parent">Settings</span>
                </a>
              </li>

        <% end %>
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>

</aside>
<!-- END NAVIGATION -->

app/views/projects/_top_nav.html.erb
<header id="header">
  <div id="logo-group">

    <!-- PLACE YOUR LOGO HERE -->
    <span id="logo" class='font-md'>
      <img src="/SmartAdmin/img/logo2.png" alt="SmartAdmin">
      <b><span class='text-primary'>Huddle</span><span class='txt-color-green'>Up</span></b>
    </span>
    <!-- END LOGO PLACEHOLDER -->



  </div>

  <!-- #TOGGLE LAYOUT BUTTONS -->
  <!-- pulled right: nav area -->
  <div class="pull-right">

    <% if current_user %>

        <!-- user settings button -->
        <div id="user_settings" class="btn-header pull-right">
                <span> <a href="/users/edit" title="My Settings"><i
                class="fa fa-user"></i></a></span>
        </div>

        <!-- collapse menu button -->
        <div id="hide-menu" class="btn-header pull-right">
                <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i
                class="fa fa-reorder"></i></a> </span>
        </div>

        <!-- logout button -->
        <div id="logout" class="btn-header transparent pull-right">
          <span> <a href="/users/sign_out" data-method='delete' title="Sign Out" data-action="userLogout"
                    data-logout-msg="You can improve your security further after logging out by closing this opened browser">
                    <i class="fa fa-sign-out"></i>
                 </a>
          </span>
        </div>

        <!-- fullscreen button -->
        <div id="fullscreen" class="btn-header transparent pull-right">
            <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i
            class="fa fa-arrows-alt"></i></a> </span>
        </div>

  <% end %>

  </div>
  <!-- end pulled right: nav area -->

</header>

app/views/projects/index.html.erb
<!-- row -->
<div class="row">

  <!-- col -->
  <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
    <h1 class="page-title txt-color-blueDark">
      <!-- PAGE HEADER -->
      <i class="fa-fw fa fa-road"></i>
      <%= @projects.count %> Projects
    </h1>
  </div>
  <!-- end col -->

  <div class="col-xs-12 col-sm-3 col-md-3 col-lg-5 pull-right">
    <!-- Button trigger modal -->
    <% if can? :create, Project %>
        <%= link_to '<i class="fa fa-plus"></i> Create a new project'.html_safe, new_project_path, :class => 'pull-right', :style => 'margin-right:22px; margin-top:10px;' %>
    <% end %>
  </div>

</div>
<!-- end row -->


<!-- row -->
<div class="row">

  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <% @projects.each do |project| %>

        <div class="panel panel-<%= get_project_status_color(project) %>">

          <div class="panel-heading">
            <h3 class="panel-title font-lg">
              <a href='/projects/<%= project.id %>'>
                <strong><%= project.name %></strong></a>
              <span class="pull-right"><%= get_project_status_text(project) %></span>
            </h3>

          </div>

          <div class="panel-body">
            <p> <%= project.description %>
                Created on <%= project.created_at.strftime("%m/%d/%Y") %>. Last updated by <%= project.get_last_updated_by %>.
            </p>

            <p>
            <table width='100%'>
              <tr>
                <td style='width:25%'><span class='font-xl'>0</span> alerts</td>
                <td style='width:25%'>
                  <span class='font-xl'><%= project.how_many_todos_left_for_this_member(current_user) %></span> todos
                  for me
                </td>
                <td style='width:25%'>
                  <span class='font-xl'><%= project.how_many_issues_left_for_this_member(current_user) %></span>
                  issues for me
                </td>
                <td style='width:25%'><span class='font-xl'><%= project.how_many_active_announcements %></span>
                  announcements
                </td>
              </tr>
            </table>
            </p>
          </div>

        </div>

    <% end %>

  </div>

</div>



<%= render :partial => '/projects/scripts' %>

<script type="text/javascript">

    $(document).ready(function () {
        pageSetUp();
    });

</script>